### ISSUE TITLE
How do DLCs play a role in this protocol? 

### ISSUE THREAD

**Issue by matthewjablack** [D33r-Gee/rootUSD-Prototype#1]
Was just reading through the project and had some questions I was curious about

My understanding is that Alisha is locking her sats into a DLC which is essentially backing the rUSD using a 1x short. When Alisha burns her rUSD, the oracle then creates the signatures that allow her to unlock the sats in the DLC. Is this understanding correct?

Who is the counterparty for the DLC that Alisha is entering? Are they required to store their funds in the DLC until someone decides to burn their rUSD? 

Is Alisha the only person that can burn? Or every time rUSD is transferred, does the DLC also need to be transferred to a new person doing a 1x short? Transferability of DLCs requires both parties to be online which seems like a big problem. Also if you're just transferring the DLC, why not just use the 1x short DLC in the first place?

What about the liquidation case? What if the Bitcoin price decreases dramatically, causing Alisha's counterparty in the DLC to be liquidated, or there not being enough capital to cover the rUSD? Does someone need to come and burn rUSD? 

Perhaps I'm misunderstanding something?

**Comment by D33r-Gee** [comment]
Hi  Matthew,

Thanks for checking out this project and for the great questions.

I’ll answer your questions first then provide context:

> My understanding is that Alisha is locking her sats into a DLC which is essentially backing the rUSD using a 1x short. When Alisha burns her rUSD, the oracle then creates the signatures that allow her to unlock the sats in the DLC. Is this understanding correct?

 The initial thought didn’t account for a 1x short. In this case Alisha wouldn’t be the one burning the rUSD, it would be the Oracle or any entity or peer that could exchange the rUSd for fiat (i.e. CashApp, Strike, Lightning ATM Operators).

>Who is the counterparty for the DLC that Alisha is entering? Are they required to store their funds in the DLC until someone decides to burn their rUSD?

In this case the counterparty is the Oracle or a Network of trusted peers or entities. The funds would not necessarily need to be stored in the DLC. In this case Alisha exchanged her sats for rUSD and can spend the rUSD like fiat with whoever accepts it. 
It doesn’t necessarily guarantee that she can redeem her rUSD for the same amount of sats. What is stored in the DLC is the proof that sats were exchanged for rUSD.

>Is Alisha the only person that can burn? Or every time rUSD is transferred, does the DLC also need to be transferred to a new person doing a 1x short? Transferability of DLCs requires both parties to be online which seems like a big problem. Also if you're just transferring the DLC, why not just use the 1x short DLC in the first place?

After Alisha has acquired her rUSD there’s no exchange of DLC with others, the rUSD are transferred using the Taro protocol and all the information about the asset is stored there.

Some context to clarify, the original idea was more aligned with Galoy’s [Stablesats](https://stablesats.com/) initiative, only using Taro as the protocol and the Oracle would be a Stablecoin issuer.

After working on it it seems that minting the rUSD every time there’s an exchange is problematic, since like you pointed out, who will burn (redeem) the rUSD if the Oracle disappears. So now we are looking at a USDc scenario where the issuer of rUSD has to guarantee that it’s 100 % backed by US Treasury Bills, or some sort of exchange that would guarantee the rUSD could be exchange, maybe something like Block’s [TBD](https://tbd54566975.ghost.io/introducing-tbdex/) will prove useful here

In extreme cases like Black Swan or forced liquidation event, to be honest, I don’t have a solution that is completely decentralized, perhaps with the use of Discreet Log Contract for Difference (DLCFD) like the folks at [Sub Red Bits](https://suredbits.com/settlement-of-dlcfd/) did would be the way to go, and different mechanisms could be written for corner case, meaning in the event of a Black Swan that forces the Oracle not be able to fulfill the settlement, the DLC after some time or action would then allow for a new transaction that enables a new party to settle the contract to access the locked sats.

Would love to hear your thoughts?

**Comment by D33r-Gee** [comment]
Closing this for now. @matthewjablack Hope your questions were answered, feel free to comment if there's any other questions or concerns.
